import bcrypt from "bcryptjs";

export const Users = [
    {
      id:1,
      profilePicture: "person/1.jpg",
      username: "Noah Sam",
    },
    {
      id:2,
      profilePicture: "person/2.jpg",
      username: "Karina Wilkinson",
    },
    {
      id:3,
      profilePicture: "person/3.jpg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "person/4.jpg",
      username: "Spidey Fan 111",
    },
    {
      id:5,
      profilePicture: "person/5.jpg",
      username: "Karina lokeside",
    },
    {
      id:6,
      profilePicture: "person/6.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "person/7.jpg",
      username: "Zarya Katyanova",
    },
    {
      id:8,
      profilePicture: "person/8.png",
      username: "Chaser B. Devineaux",
    },
    {
      id:9,
      profilePicture: "person/9.png",
      username: "Genji Kari Shimada",
    },
    {
      id:10,
      profilePicture: "person/10.jpg",
      username: "Hanzo Ryu Shimada",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "My Carmen Sandiego.",
      photo: "post/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc: "Loved this scene from FFXV",
      photo: "post/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "I like bananas",
      photo: "post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc: "I heart Frozen",
      photo: "post/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "My cosplay",
      photo: "post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by seeing this image of this scenery !.",
      photo: "post/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];


  const data = {
    users: [
      {
        id:1,
        email: 'user1@example.com',
        password: bcrypt.hashSync('password1', 8),
        profilePicture: "person/1.jpg",
        username: "Noah Sam",
      },
      {
        id:2,
        email: 'user2@example.com',
        password: bcrypt.hashSync('password2', 8),
        profilePicture: "person/2.jpg",
        username: "Karina Wilkinson",
      },
      {
        id:3,
        email: 'user3@example.com',
        password: bcrypt.hashSync('password3', 8),
        profilePicture: "person/3.jpg",
        username: "Alex Durden",
      },
      {
        id:4,
        email: 'user4@example.com',
        password: bcrypt.hashSync('password4', 8),
        profilePicture: "person/4.jpg",
        username: "Spidey Fan 111",
      },
      {
        id:5,
        email: 'user5@example.com',
        password: bcrypt.hashSync('password5', 8),
        profilePicture: "person/5.jpg",
        username: "Karina lokeside",
      },
      {
        id:6,
        email: 'user6@example.com',
        password: bcrypt.hashSync('password6', 8),
        profilePicture: "person/6.jpg",
        username: "Shirley Beauchamp",
      },
      {
        id:7,
        email: 'user7@example.com',
        password: bcrypt.hashSync('password7', 8),
        profilePicture: "person/7.jpg",
        username: "Zarya Katyanova",
      },
      {
        id:8,
        email: 'user8@example.com',
        password: bcrypt.hashSync('password8', 8),
        profilePicture: "person/8.png",
        username: "Chaser B. Devineaux",
      },
      {
        id:9,
        email: 'user9@example.com',
        password: bcrypt.hashSync('password9', 8),
        profilePicture: "person/9.png",
        username: "Genji Kari Shimada",
      },
      {
        id:10,
        email: 'user10@example.com',
        password: bcrypt.hashSync('password10', 8),
        profilePicture: "person/10.jpg",
        username: "Hanzo Ryu Shimada",
      },
    
    ],
    posts: [
      {
        id: 1,
        desc: "My Carmen Sandiego.",
        photo: "post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
      },
      {
        id: 2,
        desc: "Loved this scene from FFXV",
        photo: "post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
      },
      {
        id: 3,
        desc: "I like bananas",
        photo: "post/3.jpg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
      },
      {
        id: 4,
        photo: "post/4.jpg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
      },
      {
        id: 5,
        photo: "post/5.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
      },
      {
        id: 6,
        desc: "I heart Frozen",
        photo: "post/6.jpg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
      },
      {
        id: 7,
        desc: "My cosplay",
        photo: "post/7.jpg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
      },
      {
        id: 8,
        photo: "post/8.jpg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
      },
      {
        id: 9,
        desc: "Change the world by seeing this image of this scenery !.",
        photo: "post/9.jpg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
      },
      {
        id: 10,
        photo: "post/10.jpg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
      },
    ]
  }

export default data